import type { DossierSectionDefinition } from '@/lib/dossier/sections';

export const lsSections: DossierSectionDefinition[] = [
  {
    id: 'ls-application',
    objectType: 'LS',
    code: 'LS-01',
    title: 'Заявление на экспертизу ЛС',
    description: 'Форма заявления и базовые сведения о процедуре, заявителе, препарате и производителе.',
    documentTypeId: 'doc-application',
    requiredFor: ['registration', 're-registration', 'variation'],
    npaReference: 'Приказ ҚР ДСМ-10, форма заявления на экспертизу ЛС',
    keywords: ['заявлен', 'application', 'экспертиз', 'регистрац'],
  },
  {
    id: 'ls-payment',
    objectType: 'LS',
    code: 'LS-02',
    title: 'Документы об оплате',
    description: 'Платежные документы по договору на проведение экспертизы.',
    documentTypeId: 'doc-payment',
    requiredFor: ['registration', 're-registration', 'variation'],
    npaReference: 'Приказ ҚР ДСМ-10, общий пакет документов',
    keywords: ['оплат', 'платеж', 'payment', 'счет', 'квитанц'],
  },
  {
    id: 'ls-cover-admin',
    objectType: 'LS',
    code: 'LS-03',
    title: 'Сопроводительные и административные документы',
    description: 'Письма, доверенности, административные пояснения и сведения заявителя.',
    documentTypeId: 'doc-cover-letter',
    requiredFor: [],
    npaReference: 'Приказ ҚР ДСМ-10; Решение ЕЭК №78',
    keywords: ['сопровод', 'cover', 'письм', 'доверенн', 'административ'],
  },
  {
    id: 'ls-country-registration',
    objectType: 'LS',
    code: 'LS-04',
    title: 'Регистрация в стране-производителе и других странах',
    description: 'CPP, сведения о регистрации, разрешительные документы и регистрационный статус в других странах.',
    documentTypeId: 'doc-cpp',
    requiredFor: ['registration'],
    npaReference: 'Приказ ҚР ДСМ-10, сведения о регистрации; Решение ЕЭК №78',
    keywords: ['cpp', 'фармацевтического продукта', 'регистрац в стране', 'других странах', 'free sale'],
  },
  {
    id: 'ls-gmp-manufacturing',
    objectType: 'LS',
    code: 'LS-05',
    title: 'Производство, GMP и площадки',
    description: 'GMP-сертификаты, производственные лицензии, сведения о площадках и производителях.',
    documentTypeId: 'doc-gmp',
    requiredFor: ['registration'],
    npaReference: 'Решение ЕЭК №77; Решение ЕЭК №78',
    keywords: ['gmp', 'производств', 'площадк', 'лиценз', 'manufacturer'],
  },
  {
    id: 'ls-labeling-spc-instruction',
    objectType: 'LS',
    code: 'LS-06',
    title: 'ОХЛП, инструкция, листок-вкладыш и маркировка',
    description: 'Проекты ОХЛП, инструкции, листка-вкладыша, текста маркировки и их языковые версии.',
    documentTypeId: 'doc-instruction-ru',
    requiredFor: ['registration', 're-registration', 'variation'],
    npaReference: 'Решение Совета ЕЭК №88; Приказ ҚР ДСМ-10',
    keywords: ['охлп', 'общая характеристика', 'инструкц', 'листок', 'вкладыш', 'маркиров', 'label'],
  },
  {
    id: 'ls-mockups',
    objectType: 'LS',
    code: 'LS-07',
    title: 'Макеты упаковки',
    description: 'Графические макеты первичной и вторичной упаковки.',
    documentTypeId: 'doc-mockup',
    requiredFor: ['registration', 're-registration', 'variation'],
    npaReference: 'Решение Совета ЕЭК №88; правила маркировки',
    keywords: ['макет', 'mockup', 'упаков', 'этикет', 'jpg', 'jpeg', 'png'],
  },
  {
    id: 'ls-quality-module3',
    objectType: 'LS',
    code: 'LS-08',
    title: 'Модуль 3. Качество',
    description: 'Качество, спецификации, методики контроля, производственный процесс и аналитическая валидация.',
    documentTypeId: 'doc-module3',
    requiredFor: ['registration'],
    npaReference: 'Решение ЕЭК №78, регистрационное досье ЛС',
    keywords: ['модул 3', 'module 3', '3.2', 'качество', 'спецификац', 'методик', 'валидац', 'контрол'],
  },
  {
    id: 'ls-stability',
    objectType: 'LS',
    code: 'LS-09',
    title: 'Стабильность',
    description: 'Данные по стабильности, сроку годности и условиям хранения.',
    documentTypeId: 'doc-stability',
    requiredFor: ['registration'],
    npaReference: 'Решение ЕЭК №78, модуль качества',
    keywords: ['стабил', 'shelf life', 'срок годности', 'хранен'],
  },
  {
    id: 'ls-pharmacovigilance',
    objectType: 'LS',
    code: 'LS-10',
    title: 'Фармаконадзор',
    description: 'Мастер-файл системы фармаконадзора, контактное лицо и пострегистрационные обязательства.',
    documentTypeId: 'doc-pharmacovigilance-master',
    requiredFor: ['registration'],
    npaReference: 'Решение ЕЭК №87; Решение ЕЭК №78',
    keywords: ['фармаконадзор', 'pharmacovigilance', 'psmf', 'контактн лиц', 'управления рисками'],
  },
  {
    id: 'ls-comparison',
    objectType: 'LS',
    code: 'LS-11',
    title: 'Сравнения и обоснования отличий',
    description: 'Построчное сравнение ОХЛП/инструкции, обоснования различий и таблицы изменений.',
    documentTypeId: 'doc-spc-comparison',
    requiredFor: [],
    npaReference: 'Решение Совета ЕЭК №88; Решение ЕЭК №78',
    keywords: ['сравнен', 'построч', 'отлич', 'обоснован', 'таблиц'],
  },
  {
    id: 'ls-samples',
    objectType: 'LS',
    code: 'LS-12',
    title: 'Образцы и стандартные материалы',
    description: 'Образцы препарата, стандартные образцы, реагенты и сопроводительные сведения по ним.',
    documentTypeId: 'doc-mi-registration-dossier',
    requiredFor: [],
    npaReference: 'Приказ ҚР ДСМ-10, требования к образцам при наличии',
    keywords: ['образц', 'sample', 'реагент', 'стандартн'],
  },
  {
    id: 'ls-other',
    objectType: 'LS',
    code: 'LS-99',
    title: 'Прочие материалы ЛС',
    description: 'Файлы, которые не удалось уверенно отнести к конкретному разделу досье.',
    documentTypeId: 'doc-registration-dossier',
    requiredFor: [],
    npaReference: 'Ручная классификация экспертом',
    keywords: [],
  },
];

export const miSections: DossierSectionDefinition[] = [
  {
    id: 'mi-application',
    objectType: 'MI',
    code: 'MI-01',
    title: 'Заявление на регистрацию/экспертизу МИ',
    description: 'Форма заявления и базовые сведения о медицинском изделии, производителе и заявителе.',
    documentTypeId: 'doc-mi-application',
    requiredFor: ['registration', 're-registration', 'variation'],
    npaReference: 'Приказ ҚР ДСМ-10; Решение ЕЭК №46',
    keywords: ['заявлен', 'application', 'регистрац', 'экспертиз'],
  },
  {
    id: 'mi-payment',
    objectType: 'MI',
    code: 'MI-02',
    title: 'Документы об оплате МИ',
    description: 'Платежные документы по экспертизе медицинского изделия.',
    documentTypeId: 'doc-mi-payment',
    requiredFor: ['registration', 're-registration', 'variation'],
    npaReference: 'Приказ ҚР ДСМ-10, общий пакет документов',
    keywords: ['оплат', 'платеж', 'payment', 'счет', 'квитанц'],
  },
  {
    id: 'mi-cover-admin',
    objectType: 'MI',
    code: 'MI-03',
    title: 'Сопроводительные и административные документы МИ',
    description: 'Сопроводительные письма, доверенности, сведения о производителе и уполномоченном представителе.',
    documentTypeId: 'doc-mi-cover-letter',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46',
    keywords: ['сопровод', 'cover', 'письм', 'доверенн', 'представител', 'производител'],
  },
  {
    id: 'mi-technical-tests',
    objectType: 'MI',
    code: 'MI-04',
    title: 'Технические испытания',
    description: 'Протоколы технических испытаний, подтверждающие безопасность и эффективность изделия.',
    documentTypeId: 'doc-mi-technical-tests',
    requiredFor: ['registration'],
    npaReference: 'Решение ЕЭК №46, доказательства безопасности и эффективности',
    keywords: ['техническ', 'испытан', 'протокол', 'test report', 'performance'],
  },
  {
    id: 'mi-biological-studies',
    objectType: 'MI',
    code: 'MI-05',
    title: 'Биологическое действие и токсикология',
    description: 'Биологические, токсикологические и биосовместимые исследования при применимости.',
    documentTypeId: 'doc-mi-biological-studies',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46, доказательства безопасности и эффективности',
    keywords: ['биолог', 'токсик', 'biocompat', 'биосовмест', 'cytotox'],
  },
  {
    id: 'mi-clinical',
    objectType: 'MI',
    code: 'MI-06',
    title: 'Клинические и клинико-лабораторные данные',
    description: 'Клинические испытания, клиническая оценка и клинико-лабораторные доказательства.',
    documentTypeId: 'doc-mi-clinical-trials',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46, клинические доказательства',
    keywords: ['клиничес', 'clinical', 'лаборатор', 'оценк'],
  },
  {
    id: 'mi-instructions',
    objectType: 'MI',
    code: 'MI-07',
    title: 'Инструкции и эксплуатационная документация',
    description: 'Инструкции по применению, руководство пользователя и эксплуатационные документы.',
    documentTypeId: 'doc-mi-instructions',
    requiredFor: ['registration'],
    npaReference: 'Решение ЕЭК №46; правила маркировки и эксплуатационной документации',
    keywords: ['инструкц', 'эксплуатац', 'руководств', 'manual', 'ifu'],
  },
  {
    id: 'mi-labeling',
    objectType: 'MI',
    code: 'MI-08',
    title: 'Маркировка МИ',
    description: 'Тексты маркировки, этикетки и сведения, наносимые на изделие и упаковку.',
    documentTypeId: 'doc-mi-labeling',
    requiredFor: ['registration'],
    npaReference: 'Правила маркировки медицинских изделий',
    keywords: ['маркиров', 'label', 'этикет'],
  },
  {
    id: 'mi-mockups',
    objectType: 'MI',
    code: 'MI-09',
    title: 'Макеты, фото и упаковка МИ',
    description: 'Макеты маркировки, фотографии изделия, упаковки и внешнего вида.',
    documentTypeId: 'doc-mi-mockup',
    requiredFor: ['registration'],
    npaReference: 'Правила маркировки медицинских изделий',
    keywords: ['макет', 'фото', 'photo', 'mockup', 'упаков', 'jpg', 'jpeg', 'png'],
  },
  {
    id: 'mi-qms',
    objectType: 'MI',
    code: 'MI-10',
    title: 'СМК, декларации и класс риска',
    description: 'Сертификаты системы менеджмента качества, декларации соответствия и классификационные сведения.',
    documentTypeId: 'doc-mi-qms-certificate',
    requiredFor: ['registration'],
    npaReference: 'Решение ЕЭК №46, сведения о производителе и системе качества',
    keywords: ['смк', 'qms', 'iso', '13485', 'деклара', 'класс риска', 'сертификат'],
  },
  {
    id: 'mi-sterilization',
    objectType: 'MI',
    code: 'MI-11',
    title: 'Стерилизация',
    description: 'Валидация стерилизации и стерильного барьера при применимости.',
    documentTypeId: 'doc-mi-sterilization-validation',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46, условные требования к стерильным изделиям',
    keywords: ['стерил', 'steril', 'стерильн'],
  },
  {
    id: 'mi-software',
    objectType: 'MI',
    code: 'MI-12',
    title: 'Программное обеспечение',
    description: 'Валидация ПО, кибербезопасность и сведения о программных компонентах при применимости.',
    documentTypeId: 'doc-mi-software-validation',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46, условные требования к ПО',
    keywords: ['программ', 'software', 'по ', 'кибер', 'валидац по'],
  },
  {
    id: 'mi-pms',
    objectType: 'MI',
    code: 'MI-13',
    title: 'PMS и рыночная история',
    description: 'Пострегистрационный мониторинг, история обращения, жалобы и неблагоприятные события.',
    documentTypeId: 'doc-mi-post-marketing',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46; Приказ ҚР ДСМ-320',
    keywords: ['pms', 'пострег', 'мониторинг', 'неблагоприят', 'жалоб', 'рынк'],
  },
  {
    id: 'mi-risk',
    objectType: 'MI',
    code: 'MI-14',
    title: 'Риск-менеджмент',
    description: 'Анализ рисков, управление рисками и остаточные риски изделия.',
    documentTypeId: 'doc-mi-registration-dossier',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46, доказательства безопасности',
    keywords: ['риск', 'risk', 'управлен рисками'],
  },
  {
    id: 'mi-foreign-registration',
    objectType: 'MI',
    code: 'MI-15',
    title: 'Регистрация, Free Sale и другие страны',
    description: 'Свободная продажа, регистрация или обращение изделия в других странах.',
    documentTypeId: 'doc-mi-registration-dossier',
    requiredFor: [],
    npaReference: 'Решение ЕЭК №46, сведения о регистрации и обращении',
    keywords: ['free sale', 'регистрац в других', 'других стран', 'сертификат свобод'],
  },
  {
    id: 'mi-samples',
    objectType: 'MI',
    code: 'MI-16',
    title: 'Образцы МИ',
    description: 'Образцы изделия и пояснения по их предоставлению или неприменимости.',
    documentTypeId: 'doc-samples',
    requiredFor: [],
    npaReference: 'Приказ ҚР ДСМ-10, образцы при наличии требований',
    keywords: ['образц', 'sample'],
  },
  {
    id: 'mi-other',
    objectType: 'MI',
    code: 'MI-99',
    title: 'Прочие материалы МИ',
    description: 'Файлы, которые не удалось уверенно отнести к конкретному разделу досье.',
    documentTypeId: 'doc-mi-registration-dossier',
    requiredFor: [],
    npaReference: 'Ручная классификация экспертом',
    keywords: [],
  },
];

